### ISSUE TITLE
Strange results when using / in file path

### ISSUE THREAD

**Issue by juliangaal** [dvogt23/book-summary#16]
example note structure in `$HOME/notes/src`:
```
test1/
    note1.md
SUMMARY.md
```

using `book-summary -n $HOME/notes/src/` results in this structure, trimming filenames:
```
est1/
    ote1.md
UMMARY.md
```

`book-summary -n $HOME/notes/src` without the backslash produces the correct result! Cheers

**Comment by dvogt23** [comment]
thanks for reporting that 👍🏾  will check that soon.
