### ISSUE TITLE
Not support mdbook?

### ISSUE THREAD

**Issue by WhaleFell** [dvogt23/book-summary#27]
'''
cargo install mdbook-auto-gen-summary
         mkdir ../src
         mdbook-auto-gen-summary gen .
         cp -r ./* ../src/

         mdbook init /home/runner/work/Obsidian-Notes
         mdbook build /home/runner/work/Obsidi....
'''

Error: -27 18:45:01 [ERROR] (mdbook::book::init): Summary parsing failed for file="/home/runner/work/Obsidian-Notes/src/SUMMARY.md"

**Comment by matildepark** [comment]
This is a different project. Here you `cargo install book-summary`.

**Comment by WhaleFell** [comment]
Oh, I know. thx
